---
- hosts: windows_client
  tasks:
    - name: Install Chocolatey
      win_chocolatey:
        state: present

    - name: Install NSClient++
      win_chocolatey:
        name: nsclient
        state: present

    - name: Configure NSClient++
      win_lineinfile:
        path: 'C:\\Program Files\\NSClient++\\nsclient.ini'
        regexp: 'allowed_hosts'
        line: 'allowed_hosts = <nagios_server_ip>'
        state: present

    - name: Restart NSClient++
      win_service:
        name: nscp
        state: restarted

